### ISSUE TITLE
F1 World Grand Prix: 1999 Season (USA) - Hangs after Playstation logo

### ISSUE THREAD

**Issue by rev666** [DKWDRV/DKWDRV#14]
I've tried it with two different USB devices and results were the same. When it doesn't hang at the first screen after the playstation logo, it will for sure hang at the second screen (the EIDOS FMV logo).

![rsz_f1_world_grand_prix_1999_season-1](https://github.com/DKWDRV/DKWDRV/assets/6900547/5b3394b7-762d-4cf1-8a9f-fd04f583198e)
![rsz_f1_world_grand_prix_1999_season-2](https://github.com/DKWDRV/DKWDRV/assets/6900547/8fcccbd7-5a65-4d09-b1df-80ecf2ca6016)

Tested with default options on DKWDRV and also messing with VERSTR and some other possible options. Same result everytime.
PS2 model SCPH-77006

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by LeandroFerreira445** [comment]
F1 World Grand Prix (USA) (NTSC-U)
ID: SLUS_013.44
USB
SCPH-90006
DKWDRV-1.7.6
![20240728_131750](https://github.com/user-attachments/assets/5f306f4c-fd38-4819-961c-fcb065b161ad)

it's working perfectly
