### ISSUE TITLE
Final fantasy2 Freeze opening movie

### ISSUE THREAD

**Issue by heromanss** [DKWDRV/DKWDRV#15]
I have tried 2 different usbs and changed the region code, but it still freezes.
![17136220369363136282741677491370](https://github.com/DKWDRV/DKWDRV/assets/153185336/e21fd282-3daa-4f95-a543-e9c25715aed3)

**Comment by Ghaleon7771** [comment]
This is because its missing the XA/CDDA audio. It seems like some games really need the audio channels for them to work. 
Curiously in that screen you provided is when the music starts playing... Happens the same with other games.

**Comment by heromanss** [comment]
Thank 
Problem fixed
