### ISSUE TITLE
AZITO Entering the game, there are no subtitles and it freezes

### ISSUE THREAD

**Issue by heromanss** [DKWDRV/DKWDRV#16]
Entering the game, there are no subtitles and it freezes
![1713622474191430403279158414915](https://github.com/DKWDRV/DKWDRV/assets/153185336/30093c5d-cb57-4ad3-a729-fe1354f1207f)

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by heromanss** [comment]
Thanks 
Problem fixed....
