### ISSUE TITLE
Final Doom Freezes

### ISSUE THREAD

**Issue by naxeras** [DKWDRV/DKWDRV#18]
Final Doom USA Freezes in loading screen, usb blinking but nerver pass the screen.

**Comment by Ghaleon7771** [comment]
Yes, i tried DOOM and its stuck on Loading... as well. 
Other game that has got a similar issue is Need For Speed Porsche Unleashed.

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by naxeras** [comment]
Its working greate now. Thanks
