### ISSUE TITLE
Need For Speed Porsche Unleashed stuck on first EA logo

### ISSUE THREAD

**Issue by Ghaleon7771** [DKWDRV/DKWDRV#21]
First of all i want to say THANKS A LOT to everyone involved in this awesome program to finally play the PS2 games in the best possible way. So far almost all the games i tried work flawlessly except most of them are missing audio or music. Also the VMC would be a HUGE plus.

Back to the game, the game gets stuck as soon the first Electronic Arts FMV starts playing. I suspect this is due to the missing XA/CDDA channels. Unfortunately i cant skip the FMV like other games. Happens something similar to Twisted Metal Small Brawl, but you can skip the FMV in that game.

Cheers!

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by LeandroFerreira445** [comment]
Need for Speed Porsche Unleashed (USA) (NTSC-U)
ID: SLUS_011.04
USB
SCPH-90006
DKWDRV-1.7.6
![20240728_130618](https://github.com/user-attachments/assets/f24eb8a4-7865-4af1-9e60-313894570e83)

it's working perfectly
