### ISSUE TITLE
Lunar: Silver Star Story Complete low FPS

### ISSUE THREAD

**Issue by Ghaleon7771** [DKWDRV/DKWDRV#26]
Game starts fine but as soon it starts in Dyne Monument the FPS go really low.
In Town the FPS are working fine, but as soon as you enter in the area where Luna is singing the FPS go low again...
Really strange since this is not by any means a heavy graphical game, quite the opposite, its all 2D.

**Comment by DKWDRV** [comment]
Try 1.7.6

**Comment by Ghaleon7771** [comment]
Too late, i sold my PS2 months ago lol

**Comment by LeandroFerreira445** [comment]
Lunar Silver Star Story Complete (USA) (NTSC-U)
ID: SLUS_06.28
USB
SCPH-90006
DKWDRV-1.7.6
![Uploading 20240728_131329.jpg…]()

it's working perfectly

**Comment by LeandroFerreira445** [comment]
Lunar Silver Star Story Complete (USA) (NTSC-U)
ID: SLUS_06.28
USB
SCPH-90006
DKWDRV-1.7.6
![20240728_131329](https://github.com/user-attachments/assets/04d50557-beb4-413a-89cd-f6ae43602d05)

it's working perfectly
