### ISSUE TITLE
Hope DKWDRV works on PHATS PS2

### ISSUE THREAD

**Issue by samfadel** [DKWDRV/DKWDRV#27]
Is it any chance works on old phats ps2?

**Comment by Ghaleon7771** [comment]
Not a chance brother... unfortunately the old fat models use actual hardware to run PS1 games. Sony changed this with the Slim models using software emulation instead (or something like that im not smart for this) and that is why its possible to run via a ELF file the DKWDRV program.

**Comment by samfadel** [comment]
I think ps2 phats need loader for ps1 (like nintendont on wii ) games not software emulation
