### ISSUE TITLE
Silent Hill won’t boot

### ISSUE THREAD

**Issue by Esthrus** [DKWDRV/DKWDRV#33]
I have a few games working and the sectors / defragmenting is good but when I try to boot Silent Hill I get the ps logo then a green band appears for a second on the bottom of the screen under the logo and it crashes to black screen.

**Comment by LeandroFerreira445** [comment]
Silent Hill - DKWDRV
Link: https://youtu.be/Y5cz_JTgI_U?si=YDGuRSnDZBeahz9k

ID: SLUS_007.07

SCPH-90006

USB

**Comment by Esthrus** [comment]
Hmm off to redump my disc…

**Comment by DKWDRV** [comment]
@Esthrus works fine on all versions.
Try 1.7.6
Confirm on your side.
