### ISSUE TITLE
Mortal Kombat 3 game crashed in the first round

### ISSUE THREAD

**Issue by LeandroFerreira445** [DKWDRV/DKWDRV#34]
Vídeo
Link: https://mega.nz/folder/1K5hXQ7B#tLafgGMzSKn36Udgxj4Sog

SCPH-90006

USB

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by LeandroFerreira445** [comment]
Esta funcionando perfeitamente agora obrigado
