### ISSUE TITLE
Nightmare Creatures Does not start

### ISSUE THREAD

**Issue by LeandroFerreira445** [DKWDRV/DKWDRV#35]
ID: SLUS_005.82

SCPH-90006

USB:

Vídeo
Link: https://mega.nz/file/ISpRiaYB#4_fsjNDeghnlEEs2rVzWAW-xR13kaN8ouc5vdu6NlSI

**Comment by LeandroFerreira445** [comment]
jogos que trava por falta de audio não irei comentar

**Comment by DKWDRV** [comment]
Not a audio issue. Fixed in 1.7.6.
Confirm on your side too so we can close the issue.

**Comment by LeandroFerreira445** [comment]
Esta funcionando perfeitamente agora obrigado

**Comment by dowttie** [comment]
I can confirm this same issue in 1.7.6, it just freezes on the boot screen, sustaining a note forever.

scph-79001, loading from usb
