### ISSUE TITLE
Spider Man does not start

### ISSUE THREAD

**Issue by LeandroFerreira445** [DKWDRV/DKWDRV#38]
USB

SCPH-90006

ID: SLUS_008.75

Vídeo
Link: https://mega.nz/file/hSghGQjC#BoPdu2RxcJkPzxIUpJA1YqQukYnhVL5HpDZwIFnuPrI

**Comment by LeandroFerreira445** [comment]
jogos que trava por falta de audio não irei comentar

**Comment by DKWDRV** [comment]
Not a audio issue. Fixed in 1.7.6.
Confirm on your side too so we can close the issue.

**Comment by LeandroFerreira445** [comment]
Esta funcionando perfeitamente agora obrigado
