### ISSUE TITLE
Saru Get You SCPS_100.91 

### ISSUE THREAD

**Issue by LeandroFerreira445** [DKWDRV/DKWDRV#42]
![20240612_124207](https://github.com/DKWDRV/DKWDRV/assets/169464626/1db0069f-73ab-4116-8eaf-0c7b878844c3)

Saru Get You
ID: SCPS_100.91

USB

SCPH-90006

matrix disabled

**Comment by DKWDRV** [comment]
Fixed 1.7.6
Confirm on your side.

**Comment by LeandroFerreira445** [comment]
Esta funcionando perfeitamente agora obrigado
