### ISSUE TITLE
Army Men - Green Rogue

### ISSUE THREAD

**Issue by Sombrero28** [DKWDRV/DKWDRV#49]
**Tested with DKWDRV version**: 1.7.6
**Game ID**: SLUS-01330
**PS2 model**: SCPH-90010
**Media**: usb

**Issue**: It runs ok with no errors, just missing music.
_Game was not running in 1.7.5 version, was freezing in loading screen._

_**Tested with Matrix Infinity modchip disabled**._

**Comment by DKWDRV** [comment]
Marked as report and closed. Thank you for the report!
