### ISSUE TITLE
Resident Evil doens't recognize MC

### ISSUE THREAD

**Issue by hardlevel** [DKWDRV/DKWDRV#5]
Hi!

Just sharing the feedback, I tested Resident Evil, SLUS_0001.70, the game doesn't play the background music and voices, in game and fmv. Also when I tried to save, the memory card wasn't recognized, tested with two original MC and MemCard PRO 2.

**Comment by hardlevel** [comment]
Yes i read it, i'm not complaining,  just giving the feedback

Em qui., 18 de abr. de 2024, 01:52, rev666 ***@***.***>
escreveu:

**Comment by hardlevel** [comment]
And yes, I used ps1 mc

Em qui., 18 de abr. de 2024, 07:43, Rafael ***@***.***>
escreveu:

**Comment by DKWDRV** [comment]
Game needs PS1 MC in first slot.
