### ISSUE TITLE
MDK

### ISSUE THREAD

**Issue by Sombrero28** [DKWDRV/DKWDRV#50]
**Tested with DKWDRV version**: 1.7.6
**Game ID**: SLUS-00426
**PS2 model**: SCPH-90010
**Media**: usb

**Issue**: It runs ok, but with missing music.
If Polygon MMAG and Polygon MMIN is set to 1 = it causes small glitches to the sky, when in sniper mode.
To fix, just set both Polygon MMAG and Polygon MMIN to 0

Polygon MMAG and Polygon MMIN = 1
![VID_20240725](https://github.com/user-attachments/assets/1054d3a6-056d-4169-b74c-0ec7933aefa6)

Polygon MMAG and Polygon MMIN = 0
![VID_20240725_2](https://github.com/user-attachments/assets/3d8631be-49cd-4e28-b0b3-dc9f8d0c602a)

_**Tested with Matrix Infinity modchip disabled**._

**Comment by DKWDRV** [comment]
I am interested in improvements or regression that you can find. Graphics issue, flickering, extreme delays and any other issues.

What exactly is the glitch in this case? I am not familiar with the game.

**Comment by Sombrero28** [comment]
Think I found a solution. If Polygon MMAG and Polygon MMIN is set to 1, will cause these errors. But when I set both to 0 it get fixed!

**Comment by DKWDRV** [comment]
Those two settings are the same as setting Texture Options in OSDSYS for PS1DRV settings. This seems to be one of the games that is simply not compatible with it.
You can also toggle this options live in-game with key combos.
